apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine
  namespace: argocd
spec:
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: redmine
    targetRevision: x
    helm:
      valueFiles:
        - $values/03_REDMINE/values.yaml
  - repoURL: 'https://github.com/JasperHDB/deployment-exercises-JasperHDB.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redmine
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true