ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
  hosts: support.67.co.ucll.cloud
  tls: redmine-tls

redmineUsername: admin
redminePassword: password

databaseType: postgresql

mariadb:
  enabled: false

postgresql:
  enabled: true
  postgresqlDatabase: redmine
  postgresqlUsername: redmine
  postgresqlPassword: password